# Netlify Configuration File
# Configurações para o site de referência D&D

# Configurações básicas do site
[build]
  publish = "."
  command = "echo 'No build command needed'"

# Redirecionamentos e reescritas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeçalhos HTTP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' https://cdnjs.cloudflare.com;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
